# Ansible Inventory - Generated by Terraform
# This file is auto-generated. Do not edit manually.

[firewall]
${firewall.name} vmid=${firewall.vmid}

[dev_cluster]
%{ for name, vm in dev_vms ~}
${name} vmid=${vm.vmid} role=${vm.role}
%{ endfor ~}

[dev_masters]
%{ for name, vm in dev_vms ~}
%{ if vm.role == "master" ~}
${name} vmid=${vm.vmid}
%{ endif ~}
%{ endfor ~}

[dev_workers]
%{ for name, vm in dev_vms ~}
%{ if vm.role == "worker" ~}
${name} vmid=${vm.vmid}
%{ endif ~}
%{ endfor ~}

[dev_mgmt]
%{ for name, vm in dev_vms ~}
%{ if vm.role == "mgmt" ~}
${name} vmid=${vm.vmid}
%{ endif ~}
%{ endfor ~}

[prod_cluster]
%{ for name, vm in prod_vms ~}
${name} vmid=${vm.vmid} role=${vm.role}
%{ endfor ~}

[prod_masters]
%{ for name, vm in prod_vms ~}
%{ if vm.role == "master" ~}
${name} vmid=${vm.vmid}
%{ endif ~}
%{ endfor ~}

[prod_workers]
%{ for name, vm in prod_vms ~}
%{ if vm.role == "worker" ~}
${name} vmid=${vm.vmid}
%{ endif ~}
%{ endfor ~}

[prod_mgmt]
%{ for name, vm in prod_vms ~}
%{ if vm.role == "mgmt" ~}
${name} vmid=${vm.vmid}
%{ endif ~}
%{ endfor ~}

[infra]
%{ for name, vm in infra_vms ~}
${name} vmid=${vm.vmid} role=${vm.role}
%{ endfor ~}

[all:vars]
# SSH configuration
ansible_user=debian
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3

