# Ansible Inventory - Generated by Terraform
# DO NOT EDIT MANUALLY - This file is auto-generated
# Groups: ${join(", ", keys(ansible_groups))}

%{ for group_name, vms in ansible_groups ~}
[${group_name}]
%{ for vm in vms ~}
${vm.name} ansible_host=${vm.ip} ansible_user=${vm.user}
%{ endfor ~}

%{ endfor ~}

